### ISSUE TITLE
Training MLN

### ISSUE THREAD

**Issue by davircarvalho** [AjeetGitHub2016/HRTF-Personalization#1]
Hello, 
I'm working on this very subject as my graduation final project, in acoustical engineering school.
I'm trying to run your code, but when I get to the MLN.m routine (I suppose I should run as the last one), but MatLab can't initialize 'scaling' variable (line 41).  Would you help me?

**Comment by ljmm0405** [comment]
> Hello,
> I'm working on this very subject as my graduation final project, in acoustical engineering school.
> I'm trying to run your code, but when I get to the MLN.m routine (I suppose I should run as the last one), but MatLab can't initialize 'scaling' variable (line 41).  Would you help me?

Hello, have you solved it?

**Comment by davircarvalho** [comment]
I ended up writing my own code, but if you initialize `scaling = 1;` you might be able to run it. but is hard to say if that was the real intention as there are no comments at all
